#include "opcode_table.h"

const OpcodeInfo opcode_table[202] = {
    /* Constants */
    {"nop", NULL},
    {"aconst_null"},
    {"iconst_m1", &iconst_i},
    {"iconst_0", &iconst_i},
    {"iconst_1", &iconst_i},
    {"iconst_2", &iconst_i},
    {"iconst_3", &iconst_i},
    {"iconst_4", &iconst_i},
    {"iconst_5", &iconst_i},
    {"lconst_0"},
    {"lconst_1"},
    {"fconst_0", &fconst_f},
    {"fconst_1", &fconst_f},
    {"fconst_2", &fconst_f},
    {"dconst_0", &dconst_d},
    {"dconst_1", &dconst_d},
    {"bipush", &bipush},
    {"sipush", &sipush},
    {"ldc", &ldc_},
    {"ldc_w", &ldc_},
    {"ldc2_w", &ldc_},

    /* Loads */
    {"iload", &_load},
    {"lload"},
    {"fload"},
    {"dload"},
    {"aload", &_load},
    {"iload_0", &iload_n},
    {"iload_1", &iload_n},
    {"iload_2", &iload_n},
    {"iload_3", &iload_n},
    {"lload_0", &lload_n},
    {"lload_1", &lload_n},
    {"lload_2", &lload_n},
    {"lload_3", &lload_n},
    {"fload_0"},
    {"fload_1"},
    {"fload_2"},
    {"fload_3"},
    {"dload_0", &dload_n},
    {"dload_1", &dload_n},
    {"dload_2", &dload_n},
    {"dload_3", &dload_n},
    {"aload_0", &aload_n},
    {"aload_1", &aload_n},
    {"aload_2", &aload_n},
    {"aload_3", &aload_n},
    {"iaload", &Taload},
    {"laload", &Taload},
    {"faload", &Taload},
    {"daload", &Taload},
    {"aaload", &Taload},
    {"baload", &Taload},
    {"caload", &Taload},
    {"saload", &Taload},
    {"istore", &istore},
    {"lstore"},
    {"fstore"},
    {"dstore"},
    {"astore", &astore},
    {"istore_0", &istore_n},
    {"istore_1", &istore_n},
    {"istore_2", &istore_n},
    {"istore_3", &istore_n},
    {"lstore_0"},
    {"lstore_1"},
    {"lstore_2"},
    {"lstore_3"},
    {"fstore_0"},
    {"fstore_1"},
    {"fstore_2"},
    {"fstore_3"},
    {"dstore_0", &dstore_n},
    {"dstore_1", &dstore_n},
    {"dstore_2", &dstore_n},
    {"dstore_3", &dstore_n},
    {"astore_0", &astore_n},
    {"astore_1", &astore_n},
    {"astore_2", &astore_n},
    {"astore_3", &astore_n},
    {"iastore", &Tastore},
    {"lastore", &Tastore},
    {"fastore", &Tastore},
    {"dastore", &Tastore},
    {"aastore", &Tastore},
    {"bastore", &Tastore},
    {"castore", &Tastore},
    {"sastore", &Tastore},

    /* Operand Stack */
    {"pop"},
    {"pop2"},
    {"dup", &dup},
    {"dup_x1"},
    {"dup_x2"},
    {"dup2", &dup2},
    {"dup2_x1"},
    {"dup2_x2"},
    {"swap"},

    /* Arithmetic */
    {"iadd", &iadd},
    {"ladd"},
    {"fadd"},
    {"dadd", &dadd},
    {"isub", &isub},
    {"lsub", &lsub},
    {"fsub"},
    {"dsub", &dsub},
    {"imul", &imul},
    {"lmul"},
    {"fmul"},
    {"dmul", &dmul},
    {"idiv"},
    {"ldiv"},
    {"fdiv"},
    {"ddiv", &ddiv},
    {"irem"},
    {"lrem"},
    {"frem"},
    {"drem", &drem},
    {"ineg"},
    {"lneg"},
    {"fneg"},
    {"dneg", &dneg},
    {"ishl"},
    {"lshl"},
    {"ishr"},
    {"lshr"},
    {"iushr"},
    {"lushr"},
    {"iand"},
    {"land"},
    {"ior"},
    {"lor"},
    {"ixor"},
    {"lxor"},
    {"iinc", &iinc},

    /* Type conversion */
    {"i2l", &i2T},
    {"i2f", &i2T},
    {"i2d", &i2T},
    {"l2i"},
    {"l2f"},
    {"l2d"},
    {"f2i"},
    {"f2l"},
    {"f2d"},
    {"d2i", &d2T},
    {"d2l", &d2T},
    {"d2f", &d2T},
    {"i2b", &i2T},
    {"i2c", &i2T},
    {"i2s", &i2T},

    /* Comparisons */
    {"lcmp"},
    {"fcmpl"},
    {"fcmpg"},
    {"dcmpl", &dcmp_op},
    {"dcmpg", &dcmp_op},
    {"ifeq", &if_cond},
    {"ifne", &if_cond},
    {"iflt", &if_cond},
    {"ifge", &if_cond},
    {"ifgt", &if_cond},
    {"ifle", &if_cond},
    {"if_icmpeq", &if_icmp_cond},
    {"if_icmpne", &if_icmp_cond},
    {"if_icmplt", &if_icmp_cond},
    {"if_icmpge", &if_icmp_cond},
    {"if_icmpgt", &if_icmp_cond},
    {"if_icmple", &if_icmp_cond},
    {"if_acmpeq"},
    {"if_acmpne"},

    /* Control */
    {"goto", &_goto},
    {"jsr"},
    {"ret"},
    {"tableswitch", &tableswitch},
    {"lookupswitch", &lookupswitch},
    {"ireturn", &Treturn},
    {"lreturn", &Treturn},
    {"freturn", &Treturn},
    {"dreturn", &Treturn},
    {"areturn", &Treturn},
    {"return", &_return},

    /* References */
    {"getstatic", &getstatic},
    {"putstatic"},
    {"getfield"},
    {"putfield"},
    {"invokevirtual", &invokevirtual},
    {"invokespecial", &invokespecial},
    {"invokestatic", &invokestatic},
    {"invokeinterface"},
    {"invokedynamic"},
    {"new", &new},
    {"newarray", &newarray},
    {"anewarray"},
    {"arraylength", &_arraylength},
    {"athrow"},
    {"checkcast"},
    {"instanceof"},
    {"monitorenter"},
    {"monitorexit"},

    /* Extended */
    {"wide"},
    {"multianewarray", &multianewarray},
    {"ifnull"},
    {"ifnonnull"},
    {"goto_w"},
    {"jsr_w"},
};
