#include "opcode_table.h"

const OpcodeInfo opcode_table[202] = {
    /* Constants */
    {"nop", NULL},
    {"aconst_null"},
    {"iconst_m1", &iconst_i},
    {"iconst_0", &iconst_i},
    {"iconst_1", &iconst_i},
    {"iconst_2", &iconst_i},
    {"iconst_3", &iconst_i},
    {"iconst_4", &iconst_i},
    {"iconst_5", &iconst_i},
    {"lconst_0"},
    {"lconst_1"},
    {"fconst_0"},
    {"fconst_1"},
    {"fconst_2"},
    {"dconst_0"},
    {"dconst_1"},
    {"bipush", &bipush},
    {"sipush"},
    {"ldc", &ldc},
    {"ldc_w"},
    {"ldc2_w"},

    /* Loads */
    {"iload"},
    {"lload"},
    {"fload"},
    {"dload"},
    {"aload"},
    {"iload_0", &iload_n},
    {"iload_1", &iload_n},
    {"iload_2", &iload_n},
    {"iload_3", &iload_n},
    {"lload_0"},
    {"lload_1"},
    {"lload_2"},
    {"lload_3"},
    {"fload_0"},
    {"fload_1"},
    {"fload_2"},
    {"fload_3"},
    {"dload_0"},
    {"dload_1"},
    {"dload_2"},
    {"dload_3"},
    {"aload_0", &aload_0},
    {"aload_1"},
    {"aload_2"},
    {"aload_3"},
    {"iaload"},
    {"laload"},
    {"faload"},
    {"daload"},
    {"aaload"},
    {"baload"},
    {"caload"},
    {"saload"},
    {"istore"},
    {"lstore"},
    {"fstore"},
    {"dstore"},
    {"astore"},
    {"istore_0", &istore_n},
    {"istore_1", &istore_n},
    {"istore_2", &istore_n},
    {"istore_3", &istore_n},
    {"lstore_0"},
    {"lstore_1"},
    {"lstore_2"},
    {"lstore_3"},
    {"fstore_0"},
    {"fstore_1"},
    {"fstore_2"},
    {"fstore_3"},
    {"dstore_0"},
    {"dstore_1"},
    {"dstore_2"},
    {"dstore_3"},
    {"astore_0"},
    {"astore_1"},
    {"astore_2"},
    {"astore_3"},
    {"iastore"},
    {"lastore"},
    {"fastore"},
    {"dastore"},
    {"aastore"},
    {"bastore"},
    {"castore"},
    {"sastore"},

    /* Operand Stack */
    {"pop"},
    {"pop2"},
    {"dup"},
    {"dup_x1"},
    {"dup_x2"},
    {"dup2"},
    {"dup2_x1"},
    {"dup2_x2"},
    {"swap"},

    /* Arithmetic */
    {"iadd", &iadd},
    {"ladd"},
    {"fadd"},
    {"dadd"},
    {"isub", &isub},
    {"lsub"},
    {"fsub"},
    {"dsub"},
    {"imul", &imul},
    {"lmul"},
    {"fmul"},
    {"dmul"},
    {"idiv"},
    {"ldiv"},
    {"fdiv"},
    {"ddiv"},
    {"irem"},
    {"lrem"},
    {"frem"},
    {"drem"},
    {"ineg"},
    {"lneg"},
    {"fneg"},
    {"dneg"},
    {"ishl"},
    {"lshl"},
    {"ishr"},
    {"lshr"},
    {"iushr"},
    {"lushr"},
    {"iand"},
    {"land"},
    {"ior"},
    {"lor"},
    {"ixor"},
    {"lxor"},
    {"iinc", &iinc},

    /* Type conversion */
    {"i2l"},
    {"i2f"},
    {"i2d"},
    {"l2i"},
    {"l2f"},
    {"l2d"},
    {"f2i"},
    {"f2l"},
    {"f2d"},
    {"d2i"},
    {"d2l"},
    {"d2f"},
    {"i2b"},
    {"i2c"},
    {"i2s"},

    /* Comparisons */
    {"lcmp"},
    {"fcmpl"},
    {"fcmpg"},
    {"dcmpl"},
    {"dcmpg"},
    {"ifeq", &if_cond},
    {"ifne", &if_cond},
    {"iflt", &if_cond},
    {"ifge", &if_cond},
    {"ifgt", &if_cond},
    {"ifle", &if_cond},
    {"if_icmpeq", &if_icmp_cond},
    {"if_icmpne", &if_icmp_cond},
    {"if_icmplt", &if_icmp_cond},
    {"if_icmpge", &if_icmp_cond},
    {"if_icmpgt", &if_icmp_cond},
    {"if_icmple", &if_icmp_cond},
    {"if_acmpeq"},
    {"if_acmpne"},

    /* Control */
    {"goto", &_goto},
    {"jsr"},
    {"ret"},
    {"tableswitch", &tableswitch},
    {"lookupswitch"},
    {"ireturn", &ireturn},
    {"lreturn"},
    {"freturn"},
    {"dreturn"},
    {"areturn"},
    {"return", &_return},

    /* References */
    {"getstatic", &getstatic},
    {"putstatic"},
    {"getfield"},
    {"putfield"},
    {"invokevirtual", &invokevirtual},
    {"invokespecial", &invokespecial},
    {"invokestatic", &invokestatic},
    {"invokeinterface"},
    {"invokedynamic"},
    {"new"},
    {"newarray"},
    {"anewarray"},
    {"arraylength"},
    {"athrow"},
    {"checkcast"},
    {"instanceof"},
    {"monitorenter"},
    {"monitorexit"},

    /* Extended */
    {"wide"},
    {"multianewarray"},
    {"ifnull"},
    {"ifnonnull"},
    {"goto_w"},
    {"jsr_w"},
};
